# Generated by Django 5.2.17 on 2026-08-27 18:43

import apps.accounts.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares/', verbose_name='Avatar')),
                ('tipo', models.CharField(choices=[('master', 'Master (KS TEC)'), ('cliente', 'Administrador do Cliente'), ('rh', 'Administrador RH'), ('colaborador', 'Colaborador'), ('contador', 'Contador')], db_index=True, default='colaborador', max_length=15, verbose_name='Tipo de usuário')),
                ('trocar_senha_no_proximo_login', models.BooleanField(default=False, verbose_name='Trocar senha no próximo login')),
                ('ultimo_acesso_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Último IP')),
                ('tentativas_login_falhas', models.PositiveSmallIntegerField(default=0, verbose_name='Tentativas de login falhas')),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado até')),
                ('aceite_termos_em', models.DateTimeField(blank=True, null=True, verbose_name='Aceite dos termos em')),
                ('aceite_biometria_em', models.DateTimeField(blank=True, help_text='Consentimento explícito para uso de dados faciais (LGPD).', null=True, verbose_name='Consentimento biométrico em')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ('nome_completo',),
            },
            managers=[
                ('objects', apps.accounts.models.CustomUserManager()),
            ],
        ),
    ]
