# Generated by Django 5.2.17 on 2026-08-27 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='empresas',
            field=models.ManyToManyField(blank=True, help_text='Aplicável a Admin RH e Contador. O Admin do Cliente acessa todas.', related_name='usuarios', to='clientes.empresa', verbose_name='Empresas com acesso'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['tipo', 'cliente'], name='accounts_cu_tipo_7397e4_idx'),
        ),
    ]
