# Generated by Django 5.2.17 on 2026-08-27 21:06

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Já existe um usuário com este identificador.'}, help_text='Identificador de acesso: um e-mail válido ou um CPF.', max_length=150, unique=True, validators=[apps.accounts.models.validar_email_ou_cpf], verbose_name='E-mail ou CPF'),
        ),
    ]
