# Generated by Django 5.2.17 on 2026-08-27 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('metodo', models.CharField(max_length=8, verbose_name='Método')),
                ('caminho', models.CharField(max_length=255, verbose_name='Caminho')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='Status HTTP')),
                ('duracao_ms', models.PositiveIntegerField(default=0, verbose_name='Duração (ms)')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'Requisição da API',
                'verbose_name_plural': 'Requisições da API',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('nome', models.CharField(help_text="Identifica a integração, ex.: 'ERP Domínio'.", max_length=100, verbose_name='Nome')),
                ('chave_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Hash da chave')),
                ('prefixo', models.CharField(db_index=True, max_length=12, verbose_name='Prefixo')),
                ('somente_leitura', models.BooleanField(default=True, verbose_name='Somente leitura')),
                ('ips_permitidos', models.JSONField(blank=True, default=list, help_text='Lista de IPs/CIDRs. Vazio = sem restrição de origem.', verbose_name='IPs permitidos')),
                ('rate_limit_hora', models.PositiveIntegerField(default=1000, verbose_name='Limite por hora')),
                ('ativa', models.BooleanField(db_index=True, default=True, verbose_name='Ativa')),
                ('expira_em', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True, verbose_name='Último uso')),
                ('total_requisicoes', models.PositiveBigIntegerField(default=0, verbose_name='Total de requisições')),
                ('revogada_em', models.DateTimeField(blank=True, null=True, verbose_name='Revogada em')),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
            ],
            options={
                'verbose_name': 'Chave de API',
                'verbose_name_plural': 'Chaves de API',
                'ordering': ('-created_at',),
            },
        ),
    ]
