# Generated by Django 5.2.17 on 2026-08-27 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='clientes.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='requisicaoapi',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes', to='api.apikey', verbose_name='Chave'),
        ),
        migrations.AddField(
            model_name='requisicaoapi',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_api', to='clientes.empresa', verbose_name='Empresa'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['empresa', 'ativa'], name='api_apikey_empresa_2fe811_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaoapi',
            index=models.Index(fields=['empresa', '-created_at'], name='api_requisi_empresa_963d67_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaoapi',
            index=models.Index(fields=['api_key', '-created_at'], name='api_requisi_api_key_a9a06e_idx'),
        ),
    ]
