# Generated by Django 5.2.17 on 2026-08-27 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('ponto', '0001_initial'),
        ('rh', '0001_initial'),
        ('totem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteponto',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='rh.colaborador', verbose_name='Colaborador'),
        ),
        migrations.AddField(
            model_name='ajusteponto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='clientes.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='ajusteponto',
            name='executado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_executados', to=settings.AUTH_USER_MODEL, verbose_name='Executado por'),
        ),
        migrations.AddField(
            model_name='bancohoras',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banco_horas', to='rh.colaborador', verbose_name='Colaborador'),
        ),
        migrations.AddField(
            model_name='bancohoras',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='clientes.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='escalatrabalho',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='clientes.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='fechamentomensal',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos', to='rh.colaborador', verbose_name='Colaborador'),
        ),
        migrations.AddField(
            model_name='fechamentomensal',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='clientes.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='fechamentomensal',
            name='fechado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='rh.colaborador', verbose_name='Colaborador'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='clientes.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='origem_ajuste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_gerados', to='ponto.ajusteponto', verbose_name='Ajuste de origem'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='registrado_por',
            field=models.ForeignKey(blank=True, help_text='Preenchido em ajustes manuais e registros via API.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pontos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='totem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='totem.totem', verbose_name='Totem'),
        ),
        migrations.AddField(
            model_name='ajusteponto',
            name='registro_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_aplicados', to='ponto.registroponto', verbose_name='Registro original'),
        ),
        migrations.AddIndex(
            model_name='bancohoras',
            index=models.Index(fields=['empresa', 'data'], name='ponto_banco_empresa_acc11f_idx'),
        ),
        migrations.AddIndex(
            model_name='bancohoras',
            index=models.Index(fields=['colaborador', '-data'], name='ponto_banco_colabor_483cc2_idx'),
        ),
        migrations.AddConstraint(
            model_name='bancohoras',
            constraint=models.UniqueConstraint(fields=('colaborador', 'data'), name='uniq_banco_horas_dia'),
        ),
        migrations.AddConstraint(
            model_name='escalatrabalho',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('empresa', 'nome'), name='uniq_escala_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='fechamentomensal',
            index=models.Index(fields=['empresa', 'ano', 'mes'], name='ponto_fecha_empresa_7a7d31_idx'),
        ),
        migrations.AddConstraint(
            model_name='fechamentomensal',
            constraint=models.UniqueConstraint(fields=('colaborador', 'ano', 'mes'), name='uniq_fechamento_mes'),
        ),
        migrations.AddIndex(
            model_name='registroponto',
            index=models.Index(fields=['colaborador', 'data_hora'], name='ponto_regis_colabor_d9382d_idx'),
        ),
        migrations.AddIndex(
            model_name='registroponto',
            index=models.Index(fields=['empresa', 'data_hora'], name='ponto_regis_empresa_91f356_idx'),
        ),
        migrations.AddIndex(
            model_name='registroponto',
            index=models.Index(fields=['empresa', 'nsr'], name='ponto_regis_empresa_93b61e_idx'),
        ),
        migrations.AddConstraint(
            model_name='registroponto',
            constraint=models.UniqueConstraint(fields=('empresa', 'nsr'), name='uniq_nsr_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='ajusteponto',
            index=models.Index(fields=['colaborador', '-created_at'], name='ponto_ajust_colabor_a5119e_idx'),
        ),
    ]
