# Generated by Django 5.2.17 on 2026-08-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='registrado_offline',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Registrado sem conexão'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='uuid_offline',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True, verbose_name='Identificador do coletor'),
        ),
    ]
