# Generated by Django 5.2.17 on 2026-08-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0003_registroponto_registrado_offline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancohoras',
            name='status',
            field=models.CharField(choices=[('completo', 'Completo'), ('compensado', 'Folga compensada'), ('incompleto', 'Incompleto'), ('falta', 'Falta'), ('justificado', 'Justificado'), ('atestado', 'Atestado médico'), ('folga', 'Folga / DSR'), ('feriado', 'Feriado'), ('ferias', 'Férias'), ('afastamento', 'Afastamento')], db_index=True, default='incompleto', max_length=15, verbose_name='Status do dia'),
        ),
    ]
