# Generated by Django 5.2.17 on 2026-09-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0004_alter_bancohoras_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço aproximado'),
        ),
    ]
