# Generated by Django 5.2.17 on 2026-08-27 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('data', models.DateField(db_index=True, verbose_name='Data')),
                ('abrangencia', models.CharField(choices=[('nacional', 'Nacional'), ('estadual', 'Estadual'), ('municipal', 'Municipal'), ('empresa', 'Interno da empresa')], default='nacional', max_length=12, verbose_name='Abrangência')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Município')),
                ('recorrente', models.BooleanField(default=False, help_text='Repete todo ano na mesma data.', verbose_name='Recorrente')),
                ('meio_periodo', models.BooleanField(default=False, verbose_name='Meio período')),
                ('empresa', models.ForeignKey(blank=True, help_text='Vazio = feriado válido para toda a plataforma.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feriados', to='clientes.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ('data',),
                'indexes': [models.Index(fields=['empresa', 'data'], name='core_feriad_empresa_7647fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('acao', models.CharField(choices=[('login', 'Login'), ('login_falha', 'Tentativa de login malsucedida'), ('logout', 'Logout'), ('criacao', 'Criação de registro'), ('alteracao', 'Alteração de registro'), ('exclusao', 'Exclusão de registro'), ('ponto', 'Registro de ponto'), ('ajuste_ponto', 'Ajuste manual de ponto'), ('download', 'Download de arquivo/relatório'), ('api', 'Acesso via API'), ('config', 'Alteração de configuração'), ('seguranca', 'Evento de segurança')], db_index=True, max_length=20, verbose_name='Ação')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('objeto_tipo', models.CharField(blank=True, max_length=100, verbose_name='Tipo do objeto')),
                ('objeto_id', models.CharField(blank=True, max_length=64, verbose_name='ID do objeto')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('metadados', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acesso', to='clientes.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acesso', to='clientes.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acesso', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de acesso',
                'verbose_name_plural': 'Logs de acesso',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['cliente', '-created_at'], name='core_logace_cliente_143461_idx'), models.Index(fields=['usuario', '-created_at'], name='core_logace_usuario_8ff516_idx'), models.Index(fields=['acao', '-created_at'], name='core_logace_acao_503071_idx')],
            },
        ),
    ]
