# Generated by Django 5.2.17 on 2026-08-27 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='master.plano', verbose_name='Plano'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='clientes.empresa', verbose_name='Empresa'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['ativo', 'suspenso'], name='clientes_cl_ativo_cfebc1_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['cliente', 'ativo'], name='clientes_em_cliente_225336_idx'),
        ),
    ]
