# Generated by Django 5.2.17 on 2026-08-28 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoempresa',
            name='exibir_custos_hora_extra',
            field=models.BooleanField(default=False, help_text='Mostra o valor em reais das horas extras nos relatórios. Exige que os salários estejam preenchidos.', verbose_name='Exibir custos de horas extras'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='exibir_salarios',
            field=models.BooleanField(default=False, help_text='Salário é dado sensível dentro da própria empresa. Desligado, o campo some das telas e dos relatórios do RH.', verbose_name='Exibir salários no painel'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='exigir_liveness',
            field=models.BooleanField(default=False, help_text='Pede um gesto e analisa vários quadros. Impede foto impressa e tela parada; NÃO impede vídeo gravado. Deixa o registro alguns segundos mais lento.', verbose_name='Exigir prova de vida no totem'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='minutos_entre_marcacoes',
            field=models.PositiveSmallIntegerField(default=10, help_text='Impede a batida em duplicidade por engano — o toque a mais no totem, o clique repetido. Zero desativa a trava.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Intervalo mínimo entre marcações (min)'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='regime_horas',
            field=models.CharField(choices=[('banco', 'Banco de horas (compensação)'), ('pagamento', 'Pagamento de horas extras'), ('ambos', 'Banco, com pagamento do excedente')], default='banco', help_text='Define se o excedente vira crédito no banco ou hora extra a pagar. Muda o que a exportação para a folha envia.', max_length=10, verbose_name='Regime de horas extras'),
        ),
    ]
