# Generated by Django 5.2.17 on 2026-08-28 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_configuracaoempresa_exibir_custos_hora_extra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoempresa',
            name='liveness_no_totem',
        ),
    ]
