# Generated by Django 5.2.17 on 2026-08-28 11:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_configuracaoempresa_liveness_no_totem'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo_altura_px',
            field=models.PositiveSmallIntegerField(default=64, validators=[django.core.validators.MinValueValidator(24), django.core.validators.MaxValueValidator(240)], verbose_name='Altura da logo no totem (px)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo_css',
            field=models.TextField(blank=True, help_text='Regras aplicadas à logo em todo o sistema — totem, painel e e-mails. Ex.: filter: brightness(0) invert(1); deixa a logo toda branca.', verbose_name='CSS da logo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo_deslocamento_px',
            field=models.SmallIntegerField(default=0, help_text='Negativo sobe, positivo desce. Ajusta a logo sobre a câmera.', validators=[django.core.validators.MinValueValidator(-200), django.core.validators.MaxValueValidator(200)], verbose_name='Deslocamento vertical da logo (px)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='msg_sucesso_ponto',
            field=models.CharField(default='Ponto registrado!', help_text='Use {nome} para o primeiro nome e {hora} para o horário.', max_length=120, verbose_name='Mensagem após registrar o ponto'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='slides_segundos',
            field=models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(120)], verbose_name='Segundos por imagem'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='slides_transicao',
            field=models.CharField(choices=[('fade', 'Dissolver'), ('deslizar', 'Deslizar'), ('zoom', 'Zoom suave'), ('nenhuma', 'Troca seca')], default='fade', max_length=10, verbose_name='Transição entre as imagens'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='som_confirmacao',
            field=models.BooleanField(default=True, help_text='Confirmação sonora além da visual. Numa portaria movimentada quem está de costas não vê a tela.', verbose_name='Som ao registrar o ponto'),
        ),
        migrations.CreateModel(
            name='SlideTotem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('imagem', models.ImageField(upload_to='idle_screens/', verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, max_length=120, verbose_name='Legenda')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('inicio_exibicao', models.DateField(blank=True, null=True, verbose_name='Exibir a partir de')),
                ('fim_exibicao', models.DateField(blank=True, null=True, verbose_name='Exibir até')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='clientes.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Slide do totem',
                'verbose_name_plural': 'Slides do totem',
                'ordering': ('ordem', 'created_at'),
            },
        ),
    ]
