# Generated by Django 5.2.17 on 2026-08-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_empresa_logo_altura_px_empresa_logo_css_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='config_versao',
            field=models.PositiveIntegerField(default=1, verbose_name='Versão da configuração'),
        ),
    ]
