# Generated by Django 5.2.17 on 2026-08-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_empresa_config_versao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='integracoes_liberadas',
            field=models.BooleanField(blank=True, help_text='Vazio segue o plano. Marcado libera API e webhooks mesmo em plano que não inclui; desmarcado bloqueia mesmo em plano que inclui.', null=True, verbose_name='Integrações liberadas'),
        ),
    ]
