# Generated by Django 5.2.17 on 2026-08-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_integracoes_liberadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(blank=True, help_text='Usado em kronus.online/<slug>. Deixe vazio para acesso apenas pela página geral de login.', max_length=60, null=True, unique=True, verbose_name='Endereço da empresa'),
        ),
    ]
