# Generated by Django 5.2.17 on 2026-08-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_empresa_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='demo_expira_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Demonstração expira em'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='eh_demonstracao',
            field=models.BooleanField(db_index=True, default=False, verbose_name='É demonstração'),
        ),
    ]
