# Generated by Django 5.2.17 on 2026-08-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_cliente_demo_expira_em_cliente_eh_demonstracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoempresa',
            name='apagar_foto_apos_encoding',
            field=models.BooleanField(default=False, help_text='Guardar apenas o vetor matemático do rosto, e não a foto. Reduz o dado sensível retido, conforme a LGPD.', verbose_name='Descartar fotos após gerar o embedding'),
        ),
    ]
