# Generated by Django 5.2.17 on 2026-08-28 15:01

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_configuracaoempresa_apagar_foto_apos_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(db_index=True, help_text='CNPJ para empresa, CPF para empregador pessoa física.', max_length=14, unique=True, validators=[apps.core.utils.validar_cnpj_ou_cpf], verbose_name='CNPJ ou CPF'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cei_caepf',
            field=models.CharField(blank=True, help_text='Vai no cabeçalho do AFD. Obrigatório na prática para empregador pessoa física — é o que identifica a matrícula junto à Previdência.', max_length=20, verbose_name='CEI/CAEPF/CNO'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(db_index=True, help_text='CNPJ para empresa, CPF para empregador pessoa física.', max_length=14, unique=True, validators=[apps.core.utils.validar_cnpj_ou_cpf], verbose_name='CNPJ ou CPF'),
        ),
    ]
