# Generated by Django 5.2.17 on 2026-08-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_alter_cliente_cnpj_alter_empresa_cei_caepf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cor_fundo_login',
            field=models.CharField(default='#F8FAFC', help_text='Fundo da página onde o colaborador entra.', max_length=7, verbose_name='Cor de fundo da tela de login'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo_branca_login',
            field=models.BooleanField(default=False, help_text='Marque se a tela de login tiver fundo escuro.', verbose_name='Logo branca na tela de login'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo_branca_totem',
            field=models.BooleanField(default=False, help_text='Marque se a logo some no fundo escuro do totem.', verbose_name='Logo branca no totem'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo_css',
            field=models.TextField(blank=True, help_text='Só para ajustes que as opções acima não cobrem. Ex.: opacity: .8; — vale em todas as telas.', verbose_name='CSS adicional da logo'),
        ),
    ]
