# Generated by Django 5.2.17 on 2026-08-28 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_migrar_logo_css_para_opcoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='assinatura_altura_px',
            field=models.PositiveSmallIntegerField(default=16, help_text='Tamanho da marca no rodapé da tela do totem.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(72)], verbose_name='Altura da assinatura no totem (px)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='slogan_totem',
            field=models.CharField(blank=True, help_text='Aparece sob a mensagem de boas-vindas. Em branco, usa a frase padrão do Kronus.', max_length=120, verbose_name='Frase do totem'),
        ),
    ]
