# Generated by Django 5.2.17 on 2026-08-28 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_empresa_assinatura_altura_px_empresa_slogan_totem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo_altura_px',
            field=models.PositiveSmallIntegerField(default=64, help_text='Vale para a logo da empresa e, quando ela não tiver logo, para a marca do Kronus que aparece no lugar.', validators=[django.core.validators.MinValueValidator(24), django.core.validators.MaxValueValidator(240)], verbose_name='Altura da marca no totem (px)'),
        ),
    ]
