# Generated by Django 5.2.17 on 2026-08-28 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_alter_empresa_logo_altura_px'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='msg_boas_vindas_px',
            field=models.PositiveSmallIntegerField(default=19, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(72)], verbose_name='Tamanho da mensagem de boas-vindas (px)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='msg_sucesso_px',
            field=models.PositiveSmallIntegerField(default=16, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(64)], verbose_name='Tamanho da mensagem de confirmação (px)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='slogan_px',
            field=models.PositiveSmallIntegerField(default=13, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(48)], verbose_name='Tamanho da frase do totem (px)'),
        ),
    ]
