# Generated by Django 5.2.17 on 2026-08-28 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_empresa_msg_boas_vindas_px_empresa_msg_sucesso_px_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tentativas_antes_do_cpf',
            field=models.PositiveSmallIntegerField(default=2, help_text='Depois desse número de tentativas sem reconhecer, o totem oferece o registro por CPF. Zero insiste até o tempo acabar.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Tentativas antes de oferecer o CPF'),
        ),
    ]
