# Generated by Django 5.2.17 on 2026-08-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_empresa_tentativas_antes_do_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cadastro_facial_no_totem',
            field=models.BooleanField(default=False, help_text='Libera no totem um modo de manutenção protegido por senha, para refazer a biometria dos colaboradores no próprio equipamento.', verbose_name='Permitir cadastro facial pelo totem'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha_totem',
            field=models.CharField(blank=True, help_text='Guardada com hash — nunca em texto puro.', max_length=128, verbose_name='Senha de manutenção do totem'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha_totem_definida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Senha do totem definida em'),
        ),
    ]
