# Generated by Django 5.2.17 on 2026-08-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_cliente_cadastro_facial_no_totem_cliente_senha_totem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoempresa',
            name='guardar_frames_reconhecimento',
            field=models.BooleanField(default=False, help_text='Guarda a imagem de cada tentativa no totem. Serve para diagnosticar reconhecimento — e dado biométrico sensível (LGPD Art. 11): mantenha ligado apenas durante a análise.', verbose_name='Guardar as fotos das batidas'),
        ),
    ]
