# Generated by Django 5.2.17 on 2026-08-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_configuracaoempresa_guardar_frames_reconhecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='frases_sucesso',
            field=models.TextField(blank=True, help_text='Uma por linha. O totem sorteia entre elas a cada batida. Deixe em branco para usar as frases padrão.', verbose_name='Frases após o ponto'),
        ),
    ]
