# Generated by Django 5.2.17 on 2026-08-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_empresa_frases_sucesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='frases_sorteadas',
            field=models.BooleanField(default=True, help_text='Desligado, o totem mostra sempre a primeira da lista — útil quando a mensagem faz parte do procedimento e precisa ser sempre a mesma.', verbose_name='Sortear a frase a cada batida'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='frases_sucesso',
            field=models.TextField(blank=True, help_text='Uma por linha. Deixe em branco para usar as frases padrão.', verbose_name='Frases após o ponto'),
        ),
    ]
