# Generated by Django 5.2.17 on 2026-08-29 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0021_empresa_frases_sorteadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='marca_kronus_px',
            field=models.PositiveSmallIntegerField(default=13, help_text='Tamanho da palavra Kronus no rodapé da tela do totem.', validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(48)], verbose_name='Altura da marca Kronus no totem (px)'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='assinatura_altura_px',
            field=models.PositiveSmallIntegerField(default=16, help_text='Tamanho da marca da KS TEC no rodapé da tela do totem.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(72)], verbose_name='Altura da assinatura KS TEC no totem (px)'),
        ),
    ]
