# Generated by Django 5.2.17 on 2026-08-29 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0022_empresa_marca_kronus_px_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='relogio_px',
            field=models.PositiveSmallIntegerField(default=42, help_text='Altura dos dígitos na tela ociosa do totem.', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(120)], verbose_name='Tamanho do relógio no totem (px)'),
        ),
    ]
