# Generated by Django 5.2.17 on 2026-08-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_empresa_relogio_px'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='iniciar_por_toque',
            field=models.BooleanField(default=False, help_text='Ligado, o totem só liga a câmera quando alguém toca a tela. Desligado, ele reconhece a presença sozinho.', verbose_name='Iniciar o ponto ao tocar na tela'),
        ),
    ]
