# Generated by Django 5.2.17 on 2026-08-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0024_empresa_iniciar_por_toque'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='aprendizado_facial',
            field=models.BooleanField(default=False, help_text='O cadastro facial se atualiza sozinho com as batidas mais nítidas, mantendo a maioria das referências vinda do cadastro supervisionado.', verbose_name='Aprender com as batidas'),
        ),
    ]
