# Generated by Django 5.2.17 on 2026-08-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0025_empresa_aprendizado_facial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='aprendizado_facial',
            field=models.BooleanField(default=True, help_text='O cadastro facial se atualiza sozinho com as batidas mais nítidas, mantendo a maioria das referências vinda do cadastro supervisionado.', verbose_name='Aprender com as batidas'),
        ),
    ]
