# Generated by Django 5.2.17 on 2026-09-01 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0026_alter_empresa_aprendizado_facial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraseAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('periodo', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite e madrugada')], db_index=True, max_length=10, verbose_name='Período')),
                ('tipo', models.CharField(choices=[('saudacao', 'Saudação'), ('motivacao', 'Motivação'), ('saude', 'Dica de saúde'), ('descanso', 'Descanso')], default='saudacao', max_length=10, verbose_name='Tipo')),
                ('texto', models.CharField(max_length=160, verbose_name='Texto')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Frase da tela ociosa',
                'verbose_name_plural': 'Frases da tela ociosa',
                'ordering': ('periodo', 'tipo', 'texto'),
            },
        ),
        migrations.CreateModel(
            name='ImagemAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('periodo', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite e madrugada')], db_index=True, max_length=10, verbose_name='Período')),
                ('imagem', models.ImageField(upload_to='ambiente/', verbose_name='Imagem')),
                ('titulo', models.CharField(blank=True, max_length=120, verbose_name='Título')),
                ('autor', models.CharField(blank=True, max_length=120, verbose_name='Autor')),
                ('fonte', models.URLField(help_text='Endereço da página de origem, para conferência.', max_length=500, verbose_name='Onde foi obtida')),
                ('licenca', models.CharField(help_text='Ex.: CC0, Unsplash License, Pexels License.', max_length=80, verbose_name='Licença')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativa')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Imagem da tela ociosa',
                'verbose_name_plural': 'Imagens da tela ociosa',
                'ordering': ('periodo', 'ordem', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='modo_slides',
            field=models.CharField(choices=[('ambos', 'Meus slides e o acervo do Kronus'), ('meus', 'Somente os meus slides'), ('acervo', 'Somente o acervo do Kronus')], default='ambos', max_length=10, verbose_name='O que mostrar na tela ociosa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telas_ambiente',
            field=models.BooleanField(default=True, help_text='Saudações, dicas de saúde e imagens conforme a hora do dia. Desmarque para deixar a tela ociosa só com o que você configurou.', verbose_name='Mostrar conteúdo do acervo'),
        ),
        migrations.CreateModel(
            name='ImagemOcultaPelaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_ambiente_ocultas', to='clientes.empresa', verbose_name='Empresa')),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocultada_por', to='clientes.imagemambiente', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Imagem oculta pela empresa',
                'verbose_name_plural': 'Imagens ocultas pela empresa',
                'unique_together': {('empresa', 'imagem')},
            },
        ),
    ]
