# Generated by Django 5.2.17 on 2026-09-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0027_fraseambiente_imagemambiente_empresa_modo_slides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemambiente',
            name='id_externo',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='ID na origem'),
        ),
        migrations.AlterField(
            model_name='imagemambiente',
            name='fonte',
            field=models.URLField(blank=True, help_text='Endereço da página de origem, para conferência.', max_length=500, verbose_name='Onde foi obtida'),
        ),
        migrations.AlterField(
            model_name='imagemambiente',
            name='licenca',
            field=models.CharField(blank=True, help_text='Ex.: Pexels License, CC0, Unsplash License.', max_length=80, verbose_name='Licença'),
        ),
    ]
