# Generated by Django 5.2.17 on 2026-09-01 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0028_imagemambiente_id_externo_alter_imagemambiente_fonte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='slides_segundos',
            field=models.PositiveSmallIntegerField(default=14, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(120)], verbose_name='Segundos por imagem'),
        ),
    ]
