# Generated by Django 5.2.17 on 2026-09-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0029_alter_empresa_slides_segundos'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemambiente',
            name='clara',
            field=models.BooleanField(default=False, help_text='Quando marcada, o totem escurece a logo para não sumir.', verbose_name='Imagem clara'),
        ),
    ]
