# Generated by Django 5.2.17 on 2026-09-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0030_imagemambiente_clara'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraseambiente',
            name='autor',
            field=models.CharField(blank=True, max_length=80, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='fraseambiente',
            name='texto',
            field=models.CharField(max_length=200, verbose_name='Texto'),
        ),
    ]
