# Generated by Django 5.2.17 on 2026-09-01 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0031_fraseambiente_autor_alter_fraseambiente_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='slides_segundos',
            field=models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(120)], verbose_name='Segundos por imagem'),
        ),
    ]
