# Generated by Django 5.2.17 on 2026-09-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0032_alter_empresa_slides_segundos'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo_branca_menu',
            field=models.BooleanField(default=False, help_text='Marque se a logo some no menu lateral. Vale para o administrador, o RH e o acesso do colaborador.', verbose_name='Logo branca nos menus'),
        ),
    ]
