# Generated by Django 5.2.17 on 2026-09-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0033_empresa_logo_branca_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoempresa',
            name='inicio_do_controle',
            field=models.DateField(blank=True, help_text='A partir de quando a jornada é apurada nesta empresa. Antes desta data ninguém recebe falta: o controle não existia. Em branco, vale a data de cadastro de cada colaborador.', null=True, verbose_name='Início do controle de ponto'),
        ),
    ]
