# Generated by Django 5.2.17 on 2026-08-27 18:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTotem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_totem', to='clientes.cliente', verbose_name='Cliente')),
                ('empresas', models.ManyToManyField(blank=True, help_text='Colaboradores destas empresas são reconhecidos nos totens do grupo.', related_name='grupos_totem', to='clientes.empresa', verbose_name='Empresas atendidas')),
            ],
            options={
                'verbose_name': 'Grupo de totens',
                'verbose_name_plural': 'Grupos de totens',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Totem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('identificador', models.CharField(db_index=True, help_text='Código legível, ex.: TOTEM-RECEPCAO-01.', max_length=40, unique=True, verbose_name='Identificador')),
                ('apelido', models.CharField(blank=True, max_length=100, verbose_name='Apelido')),
                ('local_instalacao', models.CharField(blank=True, max_length=150, verbose_name='Local de instalação')),
                ('modelo_tablet', models.CharField(blank=True, default='Positivo Tab 7 Vision', max_length=100, verbose_name='Modelo do tablet')),
                ('serial_tablet', models.CharField(blank=True, max_length=60, verbose_name='Serial')),
                ('em_comodato', models.BooleanField(default=False, verbose_name='Em comodato')),
                ('data_instalacao', models.DateField(blank=True, null=True, verbose_name='Data de instalação')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data de devolução')),
                ('contrato_comodato', models.FileField(blank=True, null=True, upload_to='comodatos/', verbose_name='Contrato de comodato')),
                ('token_acesso', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token de acesso')),
                ('versao_firmware', models.CharField(blank=True, max_length=20, verbose_name='Versão do app')),
                ('ultimo_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='Último heartbeat')),
                ('ultimo_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Último IP')),
                ('bateria_percentual', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bateria (%)')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('permite_fallback_cpf', models.BooleanField(default=True, help_text='Regra 6 da Seção 14: o fallback deve estar sempre disponível.', verbose_name='Permitir fallback por CPF')),
                ('segundos_tela_sucesso', models.PositiveSmallIntegerField(default=5, verbose_name='Segundos na tela de sucesso')),
                ('segundos_countdown_offline', models.PositiveSmallIntegerField(default=120, verbose_name='Segundos do countdown offline')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totens', to='clientes.empresa', verbose_name='Empresa')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='totens', to='totem.grupototem', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Totem',
                'verbose_name_plural': 'Totens',
                'ordering': ('identificador',),
            },
        ),
        migrations.CreateModel(
            name='EventoTotem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('tipo', models.CharField(choices=[('online', 'Voltou a ficar online'), ('offline', 'Ficou offline'), ('reconhecimento_ok', 'Reconhecimento bem-sucedido'), ('reconhecimento_falha', 'Falha no reconhecimento'), ('fallback_cpf', 'Registro por CPF'), ('erro', 'Erro na aplicação do totem')], db_index=True, max_length=25, verbose_name='Tipo')),
                ('detalhes', models.CharField(blank=True, max_length=255, verbose_name='Detalhes')),
                ('metadados', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('totem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='totem.totem', verbose_name='Totem')),
            ],
            options={
                'verbose_name': 'Evento do totem',
                'verbose_name_plural': 'Eventos dos totens',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='grupototem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('cliente', 'nome'), name='uniq_grupo_totem_por_cliente'),
        ),
        migrations.AddIndex(
            model_name='totem',
            index=models.Index(fields=['empresa', 'ativo'], name='totem_totem_empresa_18e2ec_idx'),
        ),
        migrations.AddIndex(
            model_name='totem',
            index=models.Index(fields=['-ultimo_heartbeat'], name='totem_totem_ultimo__71b1ae_idx'),
        ),
        migrations.AddIndex(
            model_name='eventototem',
            index=models.Index(fields=['totem', '-created_at'], name='totem_event_totem_i_1d0b21_idx'),
        ),
    ]
