# Generated by Django 5.2.17 on 2026-08-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventototem',
            name='tipo',
            field=models.CharField(choices=[('online', 'Voltou a ficar online'), ('offline', 'Ficou offline'), ('reconhecimento_ok', 'Reconhecimento bem-sucedido'), ('reconhecimento_falha', 'Falha no reconhecimento'), ('fallback_cpf', 'Registro por CPF'), ('erro', 'Erro na aplicação do totem'), ('configuracao', 'Alteração de configuração')], db_index=True, max_length=25, verbose_name='Tipo'),
        ),
    ]
