# Generated by Django 5.2.17 on 2026-08-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0002_alter_eventototem_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='recarga_solicitada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recarga solicitada em'),
        ),
    ]
