# Generated by Django 5.2.17 on 2026-08-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0003_totem_recarga_solicitada_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totem',
            name='permite_fallback_cpf',
            field=models.BooleanField(default=True, help_text='Saída de emergência do totem. Sem ela, quem o reconhecimento facial não identificar fica sem registrar o ponto.', verbose_name='Permitir digitar o CPF quando o rosto não for reconhecido'),
        ),
    ]
