# Generated by Django 5.2.17 on 2026-08-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0004_alter_totem_permite_fallback_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totem',
            name='identificador',
            field=models.CharField(blank=True, db_index=True, help_text='Gerado pelo sistema no formato KST-AAAA-NNNN. Deixe em branco para gerar.', max_length=40, unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='totem',
            name='versao_firmware',
            field=models.CharField(blank=True, help_text='Informada pelo próprio totem a cada sinal de vida.', max_length=20, verbose_name='Versão do app'),
        ),
    ]
