# Generated by Django 5.2.17 on 2026-08-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0005_alter_totem_identificador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='modo_exibicao',
            field=models.CharField(blank=True, help_text='Como a página está aberta: aplicativo instalado ou aba do navegador.', max_length=20, verbose_name='Modo de exibição'),
        ),
    ]
