# Generated by Django 5.2.17 on 2026-08-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0006_totem_modo_exibicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='recarga_total_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recarga total pedida em'),
        ),
    ]
