# Generated by Django 5.2.17 on 2026-08-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0007_totem_recarga_total_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='atende_todo_o_cliente',
            field=models.BooleanField(default=False, help_text='Colaboradores de qualquer empresa deste cliente podem bater ponto neste equipamento. A batida continua sendo registrada na empresa de cada um.', verbose_name='Atende todas as empresas do cliente'),
        ),
    ]
