# Generated by Django 5.2.17 on 2026-08-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0008_totem_atende_todo_o_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='inicio_do_ponto',
            field=models.CharField(choices=[('empresa', 'Seguir a configuração da empresa'), ('presenca', 'Reconhecer a presença automaticamente'), ('toque', 'Somente ao tocar na tela')], default='empresa', max_length=10, verbose_name='Início do reconhecimento'),
        ),
    ]
