# Generated by Django 5.2.17 on 2026-09-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0010_alter_totem_inicio_do_ponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='versao_estaticos',
            field=models.CharField(blank=True, max_length=40, verbose_name='Versão carregada'),
        ),
    ]
