# Generated by Django 5.2.17 on 2026-09-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0011_totem_versao_estaticos'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='periodo_forcado',
            field=models.CharField(blank=True, help_text='Só para conferência: fixa manhã, tarde ou noite neste equipamento, independente da hora. Vazio segue o relógio.', max_length=10, verbose_name='Forçar período da tela ociosa'),
        ),
    ]
