# Generated by Django 5.2.17 on 2026-08-27 18:43

import apps.core.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('ponto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cbo', models.CharField(blank=True, help_text='Classificação Brasileira de Ocupações.', max_length=10, verbose_name='CBO')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('salario_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário base (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='clientes.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('cpf', models.CharField(db_index=True, max_length=11, validators=[apps.core.utils.validar_cpf], verbose_name='CPF')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('nome_social', models.CharField(blank=True, max_length=150, verbose_name='Nome social')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo (texto livre)')),
                ('matricula', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Matrícula')),
                ('data_admissao', models.DateField(verbose_name='Data de admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data de demissão')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('pis_pasep', models.CharField(blank=True, max_length=11, validators=[apps.core.utils.validar_pis], verbose_name='PIS/PASEP')),
                ('ctps', models.CharField(blank=True, max_length=20, verbose_name='CTPS')),
                ('ctps_serie', models.CharField(blank=True, max_length=10, verbose_name='Série da CTPS')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='faces/perfil/', verbose_name='Foto de perfil')),
                ('face_embedding', models.BinaryField(blank=True, help_text='Vetor ArcFace (512 dims) serializado com numpy.tobytes().', null=True, verbose_name='Embedding facial')),
                ('face_registrada', models.BooleanField(db_index=True, default=False, verbose_name='Face cadastrada')),
                ('face_atualizada_em', models.DateTimeField(blank=True, null=True, verbose_name='Face atualizada em')),
                ('consentimento_biometrico', models.BooleanField(default=False, help_text='Consentimento explícito exigido pela LGPD para dado sensível.', verbose_name='Consentimento biométrico (LGPD)')),
                ('consentimento_biometrico_em', models.DateTimeField(blank=True, null=True, verbose_name='Consentimento em')),
                ('permite_ponto_web', models.BooleanField(default=True, verbose_name='Pode bater ponto pela web')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('cargo_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='rh.cargo', verbose_name='Cargo (cadastrado)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='clientes.empresa', verbose_name='Empresa')),
                ('escala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='ponto.escalatrabalho', verbose_name='Escala de trabalho')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de acesso')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ('nome_completo',),
            },
        ),
        migrations.CreateModel(
            name='Atestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('arquivo', models.FileField(help_text='PDF, JPG ou PNG (até 10MB).', upload_to='atestados/%Y/%m/', verbose_name='Arquivo')),
                ('data_inicio', models.DateField(verbose_name='Início do afastamento')),
                ('data_fim', models.DateField(verbose_name='Fim do afastamento')),
                ('cid', models.CharField(blank=True, max_length=10, verbose_name='CID')),
                ('dias', models.PositiveSmallIntegerField(default=1, editable=False, verbose_name='Dias')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], db_index=True, default='pendente', max_length=10, verbose_name='Status')),
                ('avaliado_em', models.DateTimeField(blank=True, null=True, verbose_name='Avaliado em')),
                ('motivo_rejeicao', models.CharField(blank=True, max_length=255, verbose_name='Motivo da rejeição')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atestados_avaliados', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='clientes.empresa', verbose_name='Empresa')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atestados_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atestados', to='rh.colaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Atestado',
                'verbose_name_plural': 'Atestados',
                'ordering': ('-data_inicio',),
            },
        ),
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('tipo', models.CharField(choices=[('ferias', 'Férias'), ('licenca_maternidade', 'Licença-maternidade'), ('licenca_paternidade', 'Licença-paternidade'), ('inss', 'Afastamento INSS'), ('licenca_nao_remunerada', 'Licença não remunerada'), ('suspensao', 'Suspensão'), ('outro', 'Outro')], max_length=25, verbose_name='Tipo')),
                ('data_inicio', models.DateField(verbose_name='Início')),
                ('data_fim', models.DateField(verbose_name='Fim')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('documento', models.FileField(blank=True, null=True, upload_to='afastamentos/%Y/%m/', verbose_name='Documento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='clientes.empresa', verbose_name='Empresa')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afastamentos', to='rh.colaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Afastamento',
                'verbose_name_plural': 'Afastamentos',
                'ordering': ('-data_inicio',),
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('centro_custo', models.CharField(blank=True, max_length=30, verbose_name='Centro de custo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='clientes.empresa', verbose_name='Empresa')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_gerenciados', to='rh.colaborador', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='colaborador',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='rh.departamento', verbose_name='Departamento'),
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('data', models.DateField(db_index=True, verbose_name='Data')),
                ('tipo', models.CharField(choices=[('falta', 'Falta'), ('atraso', 'Atraso'), ('saida_antecipada', 'Saída antecipada'), ('esquecimento', 'Esquecimento de batida'), ('intervalo', 'Intervalo irregular'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('arquivo_comprovante', models.FileField(blank=True, null=True, upload_to='justificativas/%Y/%m/', verbose_name='Comprovante')),
                ('abona_dia', models.BooleanField(default=True, help_text='Se marcado, o dia deixa de contar como falta/atraso no espelho.', verbose_name='Abona o dia')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], db_index=True, default='pendente', max_length=10, verbose_name='Status')),
                ('avaliada_em', models.DateTimeField(blank=True, null=True, verbose_name='Avaliada em')),
                ('parecer', models.CharField(blank=True, max_length=255, verbose_name='Parecer')),
                ('aprovada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificativas_avaliadas', to=settings.AUTH_USER_MODEL, verbose_name='Avaliada por')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificativas', to='rh.colaborador', verbose_name='Colaborador')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='clientes.empresa', verbose_name='Empresa')),
                ('solicitada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificativas_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitada por')),
            ],
            options={
                'verbose_name': 'Justificativa',
                'verbose_name_plural': 'Justificativas',
                'ordering': ('-data',),
            },
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('empresa', 'nome'), name='uniq_cargo_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='atestado',
            index=models.Index(fields=['colaborador', 'data_inicio'], name='rh_atestado_colabor_21d1ff_idx'),
        ),
        migrations.AddIndex(
            model_name='atestado',
            index=models.Index(fields=['empresa', 'status'], name='rh_atestado_empresa_1097ae_idx'),
        ),
        migrations.AddIndex(
            model_name='afastamento',
            index=models.Index(fields=['colaborador', 'data_inicio', 'data_fim'], name='rh_afastame_colabor_360017_idx'),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('empresa', 'nome'), name='uniq_departamento_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['empresa', 'ativo'], name='rh_colabora_empresa_d33755_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['cpf', 'data_nascimento'], name='rh_colabora_cpf_2c19a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='colaborador',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('empresa', 'cpf'), name='uniq_cpf_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='colaborador',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('matricula', ''), _negated=True)), fields=('empresa', 'matricula'), name='uniq_matricula_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='justificativa',
            index=models.Index(fields=['colaborador', 'data'], name='rh_justific_colabor_945921_idx'),
        ),
        migrations.AddIndex(
            model_name='justificativa',
            index=models.Index(fields=['empresa', 'status'], name='rh_justific_empresa_90fbb4_idx'),
        ),
    ]
