# Generated by Django 5.2.17 on 2026-08-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificativa',
            name='tipo',
            field=models.CharField(choices=[('folga_compensatoria', 'Folga compensatória (banco de horas)'), ('falta', 'Falta'), ('atraso', 'Atraso'), ('saida_antecipada', 'Saída antecipada'), ('esquecimento', 'Esquecimento de batida'), ('intervalo', 'Intervalo irregular'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo'),
        ),
    ]
