# Generated by Django 5.2.17 on 2026-09-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_alter_justificativa_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='ciencia_localizacao_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ciência da coleta de localização'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ciencia_localizacao_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da ciência'),
        ),
    ]
