# Generated by Django 5.2.17 on 2026-09-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_colaborador_ciencia_localizacao_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='reforco_biometrico',
            field=models.PositiveSmallIntegerField(default=0, help_text='Capturas a mais para quem tem dificuldade de ser reconhecido. Zero usa o padrão do sistema.', verbose_name='Amostras faciais adicionais'),
        ),
    ]
