# Generated by Django 5.2.17 on 2026-09-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_colaborador_reforco_biometrico'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='inicio_do_controle',
            field=models.DateField(blank=True, help_text='Exceção à data da empresa, para quem já batia ponto antes de o controle passar a valer para o grupo. Em branco, segue a empresa.', null=True, verbose_name='Início do controle para esta pessoa'),
        ),
    ]
