# Generated by Django 5.2.17 on 2026-08-27 18:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='faces/amostras/%Y/%m/', verbose_name='Imagem')),
                ('embedding', models.BinaryField(blank=True, help_text='Vetor ArcFace (512 dims) serializado com numpy.tobytes().', null=True, verbose_name='Embedding')),
                ('angulo', models.CharField(choices=[('frontal', 'Frontal'), ('esquerda', 'Perfil esquerdo'), ('direita', 'Perfil direito'), ('cima', 'Levemente acima'), ('baixo', 'Levemente abaixo')], default='frontal', max_length=10, verbose_name='Ângulo')),
                ('modelo', models.CharField(default='ArcFace', max_length=30, verbose_name='Modelo')),
                ('detector', models.CharField(default='retinaface', max_length=30, verbose_name='Detector')),
                ('qualidade', models.FloatField(blank=True, help_text='Score de nitidez/enquadramento calculado no pré-processamento.', null=True, verbose_name='Qualidade da amostra')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Registro facial',
                'verbose_name_plural': 'Registros faciais',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TentativaReconhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('resultado', models.CharField(choices=[('identificado', 'Identificado'), ('nao_identificado', 'Não identificado'), ('sem_rosto', 'Nenhum rosto detectado'), ('multiplos_rostos', 'Múltiplos rostos'), ('erro', 'Erro no processamento'), ('liveness_falha', 'Falha na prova de vida')], db_index=True, max_length=20, verbose_name='Resultado')),
                ('distancia', models.FloatField(blank=True, help_text='Abaixo do threshold configurado indica correspondência.', null=True, verbose_name='Distância cosseno')),
                ('confianca', models.FloatField(blank=True, null=True, verbose_name='Confiança (%)')),
                ('tempo_processamento_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo de processamento (ms)')),
                ('candidatos_avaliados', models.PositiveIntegerField(default=0, verbose_name='Candidatos avaliados')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='faces/tentativas/%Y/%m/', verbose_name='Frame recebido')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'Tentativa de reconhecimento',
                'verbose_name_plural': 'Tentativas de reconhecimento',
                'ordering': ('-created_at',),
            },
        ),
    ]
