# Generated by Django 5.2.17 on 2026-08-27 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('facial', '0001_initial'),
        ('rh', '0001_initial'),
        ('totem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceregistro',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_faciais', to='rh.colaborador', verbose_name='Colaborador'),
        ),
        migrations.AddField(
            model_name='tentativareconhecimento',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tentativas_reconhecimento', to='rh.colaborador', verbose_name='Colaborador identificado'),
        ),
        migrations.AddField(
            model_name='tentativareconhecimento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_reconhecimento', to='clientes.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tentativareconhecimento',
            name='totem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tentativas_reconhecimento', to='totem.totem', verbose_name='Totem'),
        ),
        migrations.AddIndex(
            model_name='faceregistro',
            index=models.Index(fields=['colaborador', 'ativo'], name='facial_face_colabor_468878_idx'),
        ),
        migrations.AddIndex(
            model_name='tentativareconhecimento',
            index=models.Index(fields=['empresa', '-created_at'], name='facial_tent_empresa_12d343_idx'),
        ),
        migrations.AddIndex(
            model_name='tentativareconhecimento',
            index=models.Index(fields=['totem', '-created_at'], name='facial_tent_totem_i_5cd860_idx'),
        ),
        migrations.AddIndex(
            model_name='tentativareconhecimento',
            index=models.Index(fields=['resultado', '-created_at'], name='facial_tent_resulta_7d60ed_idx'),
        ),
    ]
