# Generated by Django 5.2.17 on 2026-08-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceregistro',
            name='aprendida',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Aprendida de uma batida'),
        ),
    ]
