# Generated by Django 5.2.17 on 2026-08-31 17:25

import apps.facial.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial', '0003_faceregistro_aprendida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceregistro',
            name='detector',
            field=models.CharField(default=apps.facial.models._detector_em_uso, max_length=30, verbose_name='Detector'),
        ),
        migrations.AlterField(
            model_name='faceregistro',
            name='modelo',
            field=models.CharField(default=apps.facial.models._modelo_em_uso, max_length=30, verbose_name='Modelo'),
        ),
    ]
