# Generated by Django 5.2.17 on 2026-08-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial', '0004_alter_faceregistro_detector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceregistro',
            name='embedding_confirmacao',
            field=models.BinaryField(blank=True, null=True, verbose_name='Embedding de confirmação'),
        ),
    ]
