# Generated by Django 5.2.17 on 2026-08-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial', '0005_faceregistro_embedding_confirmacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativareconhecimento',
            name='confirmacao',
            field=models.CharField(blank=True, help_text='Vazio quando a distância dispensou a conferência.', max_length=12, verbose_name='Segunda opinião'),
        ),
        migrations.AddField(
            model_name='tentativareconhecimento',
            name='desfecho',
            field=models.CharField(choices=[('pendente', 'Sem desfecho registrado'), ('aguardando', 'Aguardando o segundo quadro'), ('ponto', 'Sucesso exibido e ponto registrado'), ('so_consulta', 'Identificado sem registrar (consulta)'), ('recusado', 'Recusado — nada foi gravado'), ('duplicado', 'Recusado pelo intervalo mínimo')], db_index=True, default='pendente', max_length=12, verbose_name='Desfecho'),
        ),
        migrations.AddField(
            model_name='tentativareconhecimento',
            name='modelo',
            field=models.CharField(blank=True, max_length=30, verbose_name='Modelo'),
        ),
    ]
