# Generated by Django 5.2.17 on 2026-08-27 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('empresa', models.CharField(blank=True, max_length=150, verbose_name='Empresa')),
                ('num_colaboradores', models.CharField(blank=True, max_length=30, verbose_name='Nº de colaboradores')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('origem', models.CharField(blank=True, default='landing', max_length=60, verbose_name='Origem')),
                ('situacao', models.CharField(choices=[('novo', 'Novo'), ('em_contato', 'Em contato'), ('qualificado', 'Qualificado'), ('convertido', 'Convertido'), ('descartado', 'Descartado')], default='novo', max_length=12, verbose_name='Situação')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('plano_interesse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='master.plano', verbose_name='Plano de interesse')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('url', models.URLField(max_length=500, verbose_name='URL de destino')),
                ('eventos', models.JSONField(default=list, help_text='Lista de códigos de evento.', verbose_name='Eventos assinados')),
                ('segredo', models.CharField(max_length=64, verbose_name='Segredo (HMAC)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ultima_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Última entrega')),
                ('ultimo_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Último status HTTP')),
                ('falhas_consecutivas', models.PositiveSmallIntegerField(default=0, verbose_name='Falhas consecutivas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='clientes.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('evento', models.CharField(choices=[('esquecimento_ponto', 'Esquecimento de ponto'), ('ponto_registrado', 'Ponto registrado'), ('banco_negativo', 'Banco de horas negativo'), ('atestado_pendente', 'Atestado pendente'), ('totem_offline', 'Totem offline'), ('justificativa_pendente', 'Justificativa pendente'), ('espelho_pendente', 'Assinatura de espelho pendente'), ('fraude_gps', 'Tentativa de fraude (GPS fictício)'), ('sistema', 'Aviso do sistema')], db_index=True, max_length=25, verbose_name='Evento')),
                ('nivel', models.CharField(choices=[('info', 'Informação'), ('sucesso', 'Sucesso'), ('alerta', 'Alerta'), ('erro', 'Erro')], default='info', max_length=10, verbose_name='Nível')),
                ('canal', models.CharField(choices=[('in_app', 'No sistema'), ('email', 'E-mail'), ('ambos', 'E-mail e sistema')], default='in_app', max_length=6, verbose_name='Canal')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('url_acao', models.CharField(blank=True, max_length=255, verbose_name='URL de ação')),
                ('metadados', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('lida', models.BooleanField(db_index=True, default=False, verbose_name='Lida')),
                ('lida_em', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('enviada_email', models.BooleanField(default=False, verbose_name='E-mail enviado')),
                ('enviada_email_em', models.DateTimeField(blank=True, null=True, verbose_name='E-mail enviado em')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='clientes.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['destinatario', 'lida', '-created_at'], name='notificacoe_destina_24b76b_idx'), models.Index(fields=['evento', '-created_at'], name='notificacoe_evento_7ba67c_idx')],
            },
        ),
    ]
