# Generated by Django 5.2.17 on 2026-08-28 00:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('evento', models.CharField(db_index=True, max_length=40, verbose_name='Evento')),
                ('identificador', models.UUIDField(db_index=True, verbose_name='Identificador da entrega')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload enviado')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('entregue', 'Entregue'), ('desistiu', 'Desistiu')], db_index=True, default='pendente', max_length=10, verbose_name='Status')),
                ('tentativas', models.PositiveSmallIntegerField(default=0, verbose_name='Tentativas')),
                ('ultima_tentativa', models.DateTimeField(blank=True, null=True, verbose_name='Última tentativa')),
                ('proxima_tentativa', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Próxima tentativa')),
                ('entregue_em', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Status HTTP')),
                ('resposta', models.CharField(blank=True, max_length=500, verbose_name='Resposta do receptor')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_webhook', to='clientes.empresa', verbose_name='Empresa')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='notificacoes.webhook', verbose_name='Webhook')),
            ],
            options={
                'verbose_name': 'Entrega de webhook',
                'verbose_name_plural': 'Entregas de webhook',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['webhook', '-created_at'], name='notificacoe_webhook_315436_idx'), models.Index(fields=['status', 'proxima_tentativa'], name='notificacoe_status_9a2787_idx')],
            },
        ),
    ]
