# Generated by Django 5.2.17 on 2026-08-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_entregawebhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='evento',
            field=models.CharField(choices=[('esquecimento_ponto', 'Esquecimento de ponto'), ('ponto_registrado', 'Ponto registrado'), ('banco_negativo', 'Banco de horas negativo'), ('atestado_pendente', 'Atestado pendente'), ('totem_offline', 'Totem offline'), ('justificativa_pendente', 'Justificativa pendente'), ('espelho_pendente', 'Assinatura de espelho pendente'), ('fraude_gps', 'Tentativa de fraude (GPS fictício)'), ('facial_degradado', 'Reconhecimento facial perdendo precisão'), ('sistema', 'Aviso do sistema')], db_index=True, max_length=25, verbose_name='Evento'),
        ),
    ]
