# Generated by Django 5.2.17 on 2026-08-28 03:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('ambiente', models.CharField(choices=[('sandbox', 'Sandbox (testes)'), ('producao', 'Produção')], default='sandbox', help_text='Sandbox não move dinheiro real. Troque para Produção só depois de testar.', max_length=10, verbose_name='Ambiente')),
                ('api_key', models.CharField(blank=True, help_text='Gerada no painel do ASAAS em Integrações › Chave de API.', max_length=255, verbose_name='Chave de API do ASAAS')),
                ('webhook_token', models.CharField(blank=True, help_text="Enviado pelo ASAAS no header 'asaas-access-token'. Entre 32 e 255 caracteres. Sem ele, qualquer um pode forjar uma confirmação de pagamento.", max_length=255, verbose_name='Token do webhook')),
                ('ativo', models.BooleanField(default=False, help_text='Desligado, o sistema não cria nem consulta cobranças no gateway.', verbose_name='Cobrança automática ativa')),
                ('dias_ate_vencimento', models.PositiveSmallIntegerField(default=7, verbose_name='Dias até o primeiro vencimento')),
                ('dias_tolerancia_suspensao', models.PositiveSmallIntegerField(default=5, help_text='Uma fatura vencida não suspende a conta imediatamente: boleto leva até 3 dias úteis para compensar, e suspender antes disso tira o ponto de quem já pagou.', verbose_name='Dias de tolerância após o vencimento')),
            ],
            options={
                'verbose_name': 'Configuração do gateway',
                'verbose_name_plural': 'Configuração do gateway',
            },
        ),
        migrations.CreateModel(
            name='EventoGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('identificador_externo', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID do evento')),
                ('evento', models.CharField(db_index=True, max_length=60, verbose_name='Evento')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload recebido')),
                ('processado', models.BooleanField(db_index=True, default=False, verbose_name='Processado')),
                ('processado_em', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('erro', models.TextField(blank=True, verbose_name='Erro no processamento')),
            ],
            options={
                'verbose_name': 'Evento do gateway',
                'verbose_name_plural': 'Eventos do gateway',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('status', models.CharField(choices=[('pendente', 'Aguardando primeiro pagamento'), ('ativa', 'Ativa'), ('inadimplente', 'Inadimplente'), ('cancelada', 'Cancelada'), ('teste', 'Período de teste')], db_index=True, default='pendente', max_length=15, verbose_name='Status')),
                ('ciclo', models.CharField(choices=[('MONTHLY', 'Mensal'), ('QUARTERLY', 'Trimestral'), ('SEMIANNUALLY', 'Semestral'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=15, verbose_name='Ciclo')),
                ('forma_pagamento', models.CharField(choices=[('UNDEFINED', 'Cliente escolhe na hora'), ('BOLETO', 'Boleto'), ('PIX', 'Pix'), ('CREDIT_CARD', 'Cartão de crédito')], default='UNDEFINED', max_length=15, verbose_name='Forma de pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do ciclo (R$)')),
                ('colaboradores_contratados', models.PositiveIntegerField(default=0, help_text='Acima do incluso no plano, cobrados por `preco_por_colaborador`.', verbose_name='Colaboradores contratados')),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate, verbose_name='Início')),
                ('data_fim_teste', models.DateField(blank=True, null=True, verbose_name='Fim do período de teste')),
                ('proxima_cobranca', models.DateField(blank=True, null=True, verbose_name='Próxima cobrança')),
                ('cancelada_em', models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em')),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('asaas_customer_id', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='ID do cliente no ASAAS')),
                ('asaas_subscription_id', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='ID da assinatura no ASAAS')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='clientes.cliente', verbose_name='Cliente')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='master.plano', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('vencimento', models.DateField(db_index=True, verbose_name='Vencimento')),
                ('status', models.CharField(choices=[('pendente', 'Aguardando pagamento'), ('confirmada', 'Confirmada'), ('recebida', 'Recebida'), ('vencida', 'Vencida'), ('estornada', 'Estornada'), ('cancelada', 'Cancelada')], db_index=True, default='pendente', max_length=12, verbose_name='Status')),
                ('pago_em', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('identificador_externo', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='ID no ASAAS')),
                ('link_pagamento', models.URLField(blank=True, max_length=500, verbose_name='Link de pagamento')),
                ('linha_digitavel', models.CharField(blank=True, max_length=60, verbose_name='Linha digitável')),
                ('pix_copia_cola', models.TextField(blank=True, verbose_name='Pix copia e cola')),
                ('url_nota', models.URLField(blank=True, max_length=500, verbose_name='Nota fiscal')),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='faturamento.assinatura', verbose_name='Assinatura')),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
                'ordering': ('-vencimento',),
            },
        ),
        migrations.AddIndex(
            model_name='assinatura',
            index=models.Index(fields=['status', 'proxima_cobranca'], name='faturamento_status_896326_idx'),
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['assinatura', '-vencimento'], name='faturamento_assinat_681cc0_idx'),
        ),
    ]
