# Generated by Django 5.2.17 on 2026-08-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogateway',
            name='emitir_nota_fiscal',
            field=models.BooleanField(default=False, help_text='Emite NFS-e pelo ASAAS quando a fatura é paga. Custa R$ 0,49 por documento, além da taxa da cobrança. Exige a inscrição municipal configurada no painel do ASAAS.', verbose_name='Emitir nota fiscal automaticamente'),
        ),
        migrations.AddField(
            model_name='configuracaogateway',
            name='nota_fiscal_descricao',
            field=models.CharField(blank=True, default='Licença de uso de software de ponto eletrônico', max_length=255, verbose_name='Descrição do serviço na nota'),
        ),
    ]
