# Generated by Django 5.2.17 on 2026-08-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0002_configuracaogateway_emitir_nota_fiscal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='totens_contratados',
            field=models.PositiveIntegerField(default=0, help_text='Acima do incluído no plano, cobrados por `preco_por_totem`.', verbose_name='Totens adicionais'),
        ),
    ]
