# Generated by Django 5.2.17 on 2026-08-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0003_assinatura_totens_contratados'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogateway',
            name='custo_boleto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Custo por boleto compensado (R$)'),
        ),
        migrations.AddField(
            model_name='configuracaogateway',
            name='custo_cartao_fixo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Custo fixo por transação no cartão (R$)'),
        ),
        migrations.AddField(
            model_name='configuracaogateway',
            name='custo_cartao_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa do cartão (%)'),
        ),
        migrations.AddField(
            model_name='configuracaogateway',
            name='custo_mensal_fixo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VPS, domínio, e-mail — rateado no relatório de margem.', max_digits=10, verbose_name='Custo fixo mensal da operação (R$)'),
        ),
        migrations.AddField(
            model_name='configuracaogateway',
            name='custo_nota_fiscal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Custo por nota fiscal (R$)'),
        ),
        migrations.AddField(
            model_name='configuracaogateway',
            name='custo_pix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Custo por Pix recebido (R$)'),
        ),
    ]
