# Generated by Django 5.2.17 on 2026-08-29 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0004_configuracaogateway_custo_boleto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='desconto_ate',
            field=models.DateField(blank=True, help_text='Em branco, vale enquanto a assinatura durar.', null=True, verbose_name='Desconto válido até'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='desconto_motivo',
            field=models.CharField(blank=True, help_text='Por que foi concedido. Quem for renovar daqui a um ano precisa saber se o desconto era permanente ou de campanha.', max_length=200, verbose_name='Motivo do desconto'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sobre o total do ciclo, adicionais inclusos.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto (%)'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='desconto_valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Somado ao percentual, quando houver os dois.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desconto fixo (R$)'),
        ),
    ]
