# Generated by Django 5.2.17 on 2026-08-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0005_assinatura_desconto_ate_assinatura_desconto_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='empresas_contratadas',
            field=models.PositiveIntegerField(default=0, help_text='Acima do incluído no plano, cobradas por `preco_por_empresa`.', verbose_name='Empresas adicionais'),
        ),
    ]
