# Generated by Django 5.2.17 on 2026-08-28 13:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0009_cliente_demo_expira_em_cliente_eh_demonstracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('whatsapp', models.CharField(blank=True, help_text='Somente digitos, com DDI e DDD. Ex.: 5573988310101', max_length=20, verbose_name='WhatsApp')),
                ('whatsapp_mensagem', models.CharField(default='Olá, quero conhecer o Kronus.', help_text='Texto que ja vem digitado quando a conversa abre.', max_length=255, verbose_name='Mensagem inicial do WhatsApp')),
                ('email_contato', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de contato')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone fixo')),
                ('demo_ativa', models.BooleanField(default=True, help_text='Desligado, a capa passa a oferecer apenas o contato direto.', verbose_name='Demonstração automática ativa')),
                ('demo_horas', models.PositiveSmallIntegerField(default=24, verbose_name='Duração da demonstração (horas)')),
                ('demo_limite_diario', models.PositiveSmallIntegerField(default=20, help_text='Protege contra criação automatizada em massa.', verbose_name='Limite de demonstrações por dia')),
                ('demo_colaboradores_exemplo', models.PositiveSmallIntegerField(default=8, verbose_name='Colaboradores de exemplo')),
            ],
            options={
                'verbose_name': 'Configuração comercial',
                'verbose_name_plural': 'Configuração comercial',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoDemonstracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do interessado')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('porte', models.CharField(blank=True, max_length=30, verbose_name='Nº de colaboradores')),
                ('token', models.CharField(db_index=True, max_length=43, unique=True, verbose_name='Token do link')),
                ('expira_em', models.DateTimeField(db_index=True, verbose_name='Expira em')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('expirada', 'Expirada'), ('convertida', 'Convertida em cliente'), ('cancelada', 'Cancelada')], db_index=True, default='ativa', max_length=12, verbose_name='Situação')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
                ('acessos', models.PositiveIntegerField(default=0, verbose_name='Acessos')),
                ('primeiro_acesso_em', models.DateTimeField(blank=True, null=True, verbose_name='Primeiro acesso')),
                ('ultimo_acesso_em', models.DateTimeField(blank=True, null=True, verbose_name='Último acesso')),
                ('convertida_em', models.DateTimeField(blank=True, null=True, verbose_name='Convertida em')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demonstracoes', to='clientes.cliente', verbose_name='Ambiente gerado')),
            ],
            options={
                'verbose_name': 'Solicitação de demonstração',
                'verbose_name_plural': 'Solicitações de demonstração',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'expira_em'], name='comercial_s_status_ae07e1_idx')],
            },
        ),
    ]
