# Generated by Django 5.2.17 on 2026-08-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaocomercial',
            name='demo_colaboradores_exemplo',
        ),
    ]
