# Generated by Django 5.2.17 on 2026-08-28 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_remove_configuracaocomercial_demo_colaboradores_exemplo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocomercial',
            name='logo_kronus_altura_px',
            field=models.PositiveSmallIntegerField(default=32, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(96)], verbose_name='Altura da marca Kronus no painel (px)'),
        ),
        migrations.AddField(
            model_name='configuracaocomercial',
            name='logo_kstec_altura_px',
            field=models.PositiveSmallIntegerField(default=16, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(72)], verbose_name='Altura da marca KS TEC no painel (px)'),
        ),
    ]
