# Generated by Django 5.2.17 on 2026-08-27 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('destaque', models.BooleanField(default=False, help_text='Marca o plano como recomendado.', verbose_name='Destacar na landing')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('max_empresas', models.PositiveIntegerField(default=1, verbose_name='Máx. de empresas')),
                ('max_colaboradores', models.PositiveIntegerField(default=25, verbose_name='Máx. de colaboradores')),
                ('max_totems', models.PositiveIntegerField(default=0, verbose_name='Máx. de totens')),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço mensal (R$)')),
                ('preco_por_colaborador', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço adicional por colaborador (R$)')),
                ('tem_api', models.BooleanField(default=False, verbose_name='API REST')),
                ('tem_geofencing', models.BooleanField(default=False, verbose_name='Geofencing')),
                ('tem_totem', models.BooleanField(default=False, verbose_name='Totem facial')),
                ('tem_offline', models.BooleanField(default=False, verbose_name='Modo offline do totem')),
                ('tem_banco_horas', models.BooleanField(default=True, verbose_name='Banco de horas')),
                ('tem_webhook', models.BooleanField(default=False, verbose_name='Webhooks')),
                ('tem_portal_contador', models.BooleanField(default=False, verbose_name='Portal do contador')),
                ('tem_esocial', models.BooleanField(default=False, verbose_name='Exportação eSocial')),
                ('rate_limit_api_hora', models.PositiveIntegerField(default=1000, verbose_name='Limite de requisições da API por hora')),
                ('ativo', models.BooleanField(default=True, verbose_name='Disponível para contratação')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ('ordem', 'preco_mensal'),
            },
        ),
        migrations.CreateModel(
            name='LogAcessoMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Excluído em')),
                ('acao', models.CharField(choices=[('cliente_criado', 'Cliente criado'), ('cliente_editado', 'Cliente editado'), ('cliente_suspenso', 'Cliente suspenso'), ('cliente_reativado', 'Cliente reativado'), ('empresa_vinculada', 'Empresa vinculada'), ('empresa_desvinculada', 'Empresa desvinculada'), ('plano_alterado', 'Plano alterado'), ('api_key_gerada', 'API key gerada/regenerada'), ('api_key_revogada', 'API key revogada'), ('totem_cadastrado', 'Totem cadastrado'), ('totem_comodato', 'Comodato registrado'), ('totem_devolvido', 'Totem devolvido')], max_length=25, verbose_name='Ação')),
                ('detalhes', models.TextField(blank=True, verbose_name='Detalhes')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_master', to='clientes.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_master', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Log do Master',
                'verbose_name_plural': 'Logs do Master',
                'ordering': ('-created_at',),
            },
        ),
    ]
