# Generated by Django 5.2.17 on 2026-08-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logacessomaster',
            name='acao',
            field=models.CharField(choices=[('cliente_criado', 'Cliente criado'), ('cliente_editado', 'Cliente editado'), ('cliente_suspenso', 'Cliente suspenso'), ('cliente_reativado', 'Cliente reativado'), ('empresa_vinculada', 'Empresa vinculada'), ('empresa_desvinculada', 'Empresa desvinculada'), ('plano_alterado', 'Plano alterado'), ('api_key_gerada', 'API key gerada/regenerada'), ('api_key_revogada', 'API key revogada'), ('totem_cadastrado', 'Totem cadastrado'), ('totem_comodato', 'Comodato registrado'), ('totem_devolvido', 'Totem devolvido'), ('config_alterada', 'Configuração da plataforma alterada'), ('demo_prorrogada', 'Demonstração prorrogada'), ('demo_convertida', 'Demonstração convertida em cliente'), ('demo_encerrada', 'Demonstração encerrada')], max_length=25, verbose_name='Ação'),
        ),
    ]
