# Generated by Django 5.2.17 on 2026-08-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_logacessomaster_acao'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='preco_por_totem',
            field=models.DecimalField(decimal_places=2, default=60, help_text='Cobrado por totem além do incluído no plano.', max_digits=10, verbose_name='Preço por totem adicional (R$)'),
        ),
    ]
