# Generated by Django 5.2.17 on 2026-08-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_plano_preco_por_totem'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='preco_por_empresa',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cobrado por empresa além da incluída no plano.', max_digits=10, verbose_name='Preço por empresa adicional (R$)'),
        ),
    ]
